-- Migration: prepare the utente table for bcrypt password hashes.
-- Run this script after importing VIBESHOP.sql.
--
-- Important: legacy SHA-256 hashes from the original dump cannot be verified
-- by bcrypt. After this migration, recreate seed users or reset their passwords
-- through the Java application so new hashes are generated by PasswordUtils.

USE `vibeshop`;

ALTER TABLE `utente`
    MODIFY `password_hash` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL;
